<?php

/** @var $block \Magento\Catalog\Block\Product\View */
$product = $block->getProduct();
?>
<meta name="sailthru.title" content="<?php echo htmlspecialchars($product->getName()); ?>" />
<meta name="sailthru.tags" content="<?php echo htmlspecialchars($product->getMetaKeyword()); ?>" />
<meta name="sailthru.description" content="<?php echo htmlspecialchars($product->getDescription()); ?>" />
<meta name="sailthru.image.full" content="<?php echo htmlspecialchars($product->getImageUrl()); ?>" />
<meta name="sailthru.image.thumb" content="<?php echo htmlspecialchars($product->getThumbnailUrl(50, 50)); ?>" />
<meta name="sailthru.price" content="<?php echo htmlspecialchars($product->getPrice()*100); ?>" />
