<div class="<?php echo $block->getClass() ?>">
	<h1><?php echo $block->getStatus() ?></h1>
	<h2><?php echo $block->getMessage() ?></h2>
</div>

<script>
 var params = {internUrl:"<?php echo $block->getInternUrl() ?>",  apiKeyId: "#<?php echo $block->getApiKeyId() ?>", htmlId: "#<?php echo $block->getHtmlId() ?>", loadConfigUrl: "<?php echo $block->getLoadConfigUrl() ?>"};  
         // document.querySelector("#<?php echo $block->getHtmlId() ?>").onclick = function(e){
         	console.log(params);
           // e.target.preventDefault();
           // e.target.html = params;
         // };       
</script>
