<!-- <div class="pp-buttons-container">
    <button id="<?php echo $block->getHtmlId() ?>" onclick="return false;">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div> -->
<!-- <input id="<?php echo $block->getHtmlId() ?>" name="<?php echo $block->getName(); ?>" data-ui-id="form-element-<? echo $block->getName() . ($suffix ?: '') ?>" value="<?php echo $block->getSuccess() ?>" class=" input-text admin__control-text" type="text">
 -->
<div class="<?php echo $block->getClass() ?>">
	<h1><?php echo $block->getStatus() ?></h1>
	<h2><?php echo $block->getMessage() ?></h2>
</div>

<script>
 var params = {internUrl:"<?php echo $block->getInternUrl() ?>",  apiKeyId: "#<?php echo $block->getApiKeyId() ?>", htmlId: "#<?php echo $block->getHtmlId() ?>", loadConfigUrl: "<?php echo $block->getLoadConfigUrl() ?>"};  
         // document.querySelector("#<?php echo $block->getHtmlId() ?>").onclick = function(e){
         	console.log(params);
           // e.target.preventDefault();
           // e.target.html = params;
         // };       
</script>
