<h2>Define Customer Groups from Sailthru Lists</h2>

<style>	
	#sailthru div {
		float: left;
		margin: 30px;
	}
</style>

<div id="sailthru">
	<form action="*" method="POST">
		<input type="hidden" name="form_key" value="<?php echo $form_key; ?>" />
		<div style="float: left;">
			<select name="sailthruList">
				<?php foreach ($lists as $list): ?>
					<option value="<?php echo $list['value']; ?>" ><?php echo $list["label"]; ?></option>
				<?php endforeach; ?>
			</select>	
		</div>	
		<div> ==></div>
		<div style="float: left;">
			<select name="groupId">
				<?php foreach ($customer_groups as $customer_group): ?>
					<option value="<? echo $customer_group->getId(); ?>" ><?php echo $customer_group->getCode(); ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div style="width: 100%;">
			<button type="submit">Import</button>
		</div>
	</form>
</div>
